### ISSUE TITLE
Add RSS feed for blog entries

### ISSUE THREAD

**Issue by marcells** [hiai-de/blog#8]
A RSS feed for the blogs page, which could be consumend by offline and online RSS readers.

**Comment by domhabersack** [comment]
🖐️ I’d be happy to work on this for Hacktoberfest.

**Comment by marcells** [comment]
Thank you. 👍 I did assign you.

**Comment by domhabersack** [comment]
Opened a pull request for this. With the changed rules for Hacktoberfest, I’d appreciate if you could tag the PR as “hacktoberfest-accepted” before merging it. Thanks!

EDIT: updated because it’s the PR that needs the label, not the issue.
